name: halisaha_app
description: Halı Saha Mobil Uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  dio: ^5.7.0

  # Secure storage (token saklama)
  flutter_secure_storage: ^9.2.3

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.6.2

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Form validation
  email_validator: ^3.0.0

  # Location + map
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.2
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
